### PR TITLE
Remove patch for go-sqlite3

### PR DESCRIPTION
**Pull request by tetsuok**
This fixes failure of `configure` script. On my macOS 15.2, `configure` script fails when applying the patch for `go-sqlite3` package.

```
$ ./configure
configure: I: Using Go from: /usr/local/go
configure: I: Installing git hook pre-commit
configure: I: Getting bazil.org/fuse
configure: I: Getting github.com/dustin/go-humanize
configure: I: Getting github.com/golang/glog
configure: I: Getting golang.org/x/lint/golint
configure: I: Getting github.com/mattn/go-sqlite3
configure: I: Applying patch go-sqlite3.issue-285.diff
patching file deps/src/github.com/mattn/go-sqlite3/sqlite3.go
Hunk #1 FAILED at 12.
1 out of 1 hunk FAILED -- saving rejects to file deps/src/github.com/mattn/go-sqlite3/sqlite3.go.rej
configure: E: Failed to apply go-sqlite3.issue-285.diff
```

It seems go-sqlite3 addressed the issue by updating the documentation in https://github.com/mattn/go-sqlite3/commit/c9394b1e02281de8e1d60049383d710005cc0ae5, the patch itself seems no longer necessary (at least on macOS).

---
This change is [Reviewable](https://reviewable.io/reviews/jmmv/sourcachefs/4)

### CODE REVIEW

**Comment by jmmv** [comment]
Confirmed that this doesn't seem to be necessary any longer (checked the latest `sqlite3.go` sources), though the referenced commit doesn't make that clear. Anyway, will wait for the dependent #3 PR to be submitted and this one rebased before merging.

Thanks!

**Comment by tetsuok** [comment]
Thanks for the confirmation! I'll rebase commits once #3 PR gets merged.

**Comment by jmmv** [comment]
#3 merged. Please rebase now! Thanks.

**Comment by tetsuok** [comment]
Rebased and squashed.

**Comment by tetsuok** [comment]
Thanks!

**Pull request merged**
